### PR TITLE
Support functional type defaults

### PR DESCRIPTION
**Pull request by ashconnell**
This PR aims to resolve https://github.com/gohyperr/hecs/issues/12

While this _does_ solve the issue, it also breaks some plugins that have a default that is meant to be a function.

One example of this is the `Transform` component in `hecs-plugin-core` which uses a `Vector3` as the default. This value is a function.

https://github.com/gohyperr/hecs/blob/master/packages/hecs-plugin-core/src/components/Transform.js#L21

@canadaduane i'm wondering if maybe we should use a separate key like `defaultFn`. If this exists it'll call it to get the value, otherwise it will use `default`. What do you think?

### CODE REVIEW

**Comment by ashconnell** [comment]
I've gone ahead and updated this. You can now use `default` normally but if you want to use a function you use `defaultFn`

**Comment by canadaduane** [comment]
I don't think `Transform` uses `Vector3` as the default, does it? Looking at the code, it seems to initialize as follows:
```
    scale: {
      type: Vector3Type,
      default: new Vector3(1, 1, 1),
      editor: {
        label: 'Scale',
      },
    },
```

So the `default` value would be a value there, not a function, as far as I can tell.

**Comment by canadaduane** [comment]
FWIW I'm also fine with `defaultFn`.

**Comment by ashconnell** [comment]
Not that I recommend it, someone might actually want their default to be a function, and they wouldn't be able to do it.

I think the current solution works, shall I merge?

**Comment by canadaduane** [comment]
LGTM, thanks!

**Pull request merged**
